version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: jozko/docker:pgclient
      - image: postgres:9.6.4-alpine
        environment:
          POSTGRES_PASSWORD: pgpass
          POSTGRES_USER: pguser

    steps:
      - checkout
      - setup_remote_docker

      - run:
         name: Connect to the DB
         command: psql postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1/pguser -c select 1;
